/// <reference path="./types/brittle.d.ts" />

require('./unit/tree-canonical.test.js')
require('./unit/tree-module-graph.test.js')
require('./unit/storage-tree.test.js')
require('./unit/tree-manifest.test.js')
require('./unit/tree-extract.test.js')
require('./unit/symlink-rules.test.js')
require('./unit/link-store.test.js')
require('./unit/release.test.js')
require('./unit/tar-protocol.test.js')
require('./unit/tar-session-store.test.js')
require('./unit/commit-journal.test.js')
require('./unit/commit-recovery.test.js')
require('./unit/retention.test.js')
require('./unit/direct-dht.test.js')
require('./unit/hooks.test.js')
require('./unit/direct-behavior.test.js')
require('./unit/cli.test.js')
require('./unit/files.test.js')
require('./unit/tar-property.test.js')
require('./integration/direct-upload.test.js')
require('./integration/source-parent-optout.test.js')
require('./integration/behavior-observability.test.js')
