'use strict'

require('./unit/identity.test')
require('./unit/imports.test')
require('./unit/files.test')
require('./unit/protocol.test')
require('./unit/session-store.test')
require('./unit/commit-store.test')
require('./unit/recovery.test')
require('./unit/retention.test')
require('./unit/scrub.test')
require('./unit/allowlist.test')
require('./unit/server-session.test')
require('./unit/client.test')
require('./unit/client-session.test')
require('./unit/cli.test')
require('./integration/server-auth.test')
require('./integration/upload.test')
require('./integration/resume.test')
require('./integration/cli.test')
