/// <reference path="./types/brittle.d.ts" />

require('./unit/identity.test.js')
require('./unit/imports.test.js')
if (typeof Bare === 'undefined') {
  require('./unit/imports-node.test.js')
}
require('./unit/files.test.js')
require('./unit/protocol.test.js')
require('./unit/protocol-property.test.js')
require('./unit/session-store.test.js')
require('./unit/final-review-storage.test.js')
require('./unit/commit-store.test.js')
require('./unit/recovery.test.js')
require('./unit/retention.test.js')
require('./unit/scrub.test.js')
require('./unit/allowlist.test.js')
require('./unit/server-session.test.js')
require('./unit/client.test.js')
require('./unit/client-session.test.js')
require('./unit/cli.test.js')
require('./integration/server-auth.test.js')
require('./integration/final-review.test.js')
require('./integration/upload.test.js')
require('./integration/resume.test.js')
require('./integration/adversarial.test.js')
require('./integration/revocation.test.js')
require('./integration/retention.test.js')
require('./integration/cli.test.js')
require('./integration/observability.test.js')
