/// <reference path="./types/brittle.d.ts" />

require('../test/unit/identity.test.js')
require('./unit/imports.test.js')
if (typeof Bare === 'undefined') {
  require('./unit/imports-node.test.js')
}
require('../test/unit/files.test.js')
require('../test/unit/protocol.test.js')
require('../test/unit/protocol-property.test.js')
require('../test/unit/session-store.test.js')
require('../test/unit/final-review-storage.test.js')
require('../test/unit/commit-store.test.js')
require('../test/unit/recovery.test.js')
require('../test/unit/retention.test.js')
require('../test/unit/scrub.test.js')
require('../test/unit/allowlist.test.js')
require('../test/unit/server-session.test.js')
require('../test/unit/client.test.js')
require('../test/unit/client-session.test.js')
require('../test/unit/cli.test.js')
require('../test/integration/server-auth.test.js')
require('../test/integration/final-review.test.js')
require('../test/integration/upload.test.js')
require('../test/integration/resume.test.js')
require('../test/integration/adversarial.test.js')
require('../test/integration/revocation.test.js')
require('../test/integration/retention.test.js')
require('../test/integration/cli.test.js')
require('../test/integration/observability.test.js')
